### ISSUE TITLE
[REQUEST] Please update this unique tool!

### ISSUE THREAD

**Issue by linuxmobile** [furesuka/HADRIAN#2]
Hi there. I see and try TeeArch. It's working fine and pantheon look perfect synced but i want to install pantheon in a vanilla Arch installation!! Please maintain this updated!!! Thx u

**Comment by shnflrsc** [comment]
Hello! I wasn't expecting someone to open an issue here. I will likely rework HADRIAN this week, but I haven't touched any Arch-based distros or made a bash script in quite a while so it might take some time. The current version was only tested on a virtual machine and I don't have any idea what issues will come up when it is used on real hardware.

>  It's working fine and pantheon look perfect synced

What do you mean by this? Did you test it out on a VM or a real installation, and did it work perfectly?

**Comment by linuxmobile** [comment]
> What do you mean by this? Did you test it out on a VM or a real installation, and did it work perfectly?

_On the TeArch distro pantheon works fine. Including the selection of wallpapers. I like but there's a lot of unnecessary stuff. Like intel ucode (i'm using amd)... I know how to uninstall but i like the vanilla arch build... and with your script it can be perfect for me!_

In your script you have to update some things (I'm super newbie, not that I know how to do it!) But **plank was changed to io.elementary.dock**, and some things that I think should be adjusted more!

I hope to see something of yours soon !! I love arch, but I also like pantheon! **If you need to test something on real hardware. Here I am!**

**Comment by shnflrsc** [comment]
Thank you for offering help in the development! I understand there are a couple things to change in the script, but I hardly remember how my script works haha. I only used Google searches to complete it. Anyway, _While still being an experienced noob_, I plan to rework it with the following features:

- **use [ncurses Dialog](https://www.filebuzz.com/software_screenshot/full/mybashburn-448351.jpeg) for a friendlier experience.** Archfi and Void Linux both uses ncurses Dialog and I like how it looks, so I will be implementing them here. Learning will take some time...
- **Make the script more organized.** This will help in readability and maintainability. I'll probably split the installation stages and the list of packages to install into different scripts.
- **Make Pantheon actually work.** The current version doesn't work well at all even in a virtual machine. _TeArch_ managed to do it...
- **Rework README.md.** Will show an about section and an installation section only. Other information will be stated in the script before proceeding.

That's all I can think of right now. What you need to know right now is that they are working on making Pantheon [distro-agnostic](https://github.com/orgs/elementary/projects/46) and they seem to be halfway there! That means they will make it easier for people on other distros to install Pantheon. I don't know if this script will still be necessary when they complete it. I'll still work on HADRIAN as a fun project.

**Comment by linuxmobile** [comment]
> Thank you for offering help in the development! I understand there are a couple things to change in the script, but I hardly remember how my script works haha. I only used Google searches to complete it. Anyway, _While still being an experienced noob_, I plan to rework it with the following features:
> 
>     * **use [ncurses Dialog](https://www.filebuzz.com/software_screenshot/full/mybashburn-448351.jpeg) for a friendlier experience.** Archfi and Void Linux both uses ncurses Dialog and I like how it looks, so I will be implementing them here. Learning will take some time...
> 
>     * **Option for an automatic installation.** This option will install Pantheon without any customization.
> 
>     * **Make the script more organized.** This will help in readability and maintainability. I'll probably split the installation stages and the list of packages to install into different scripts.
> 
>     * **Make Pantheon actually work.** The current version doesn't work well at all even in a virtual machine. _TeArch_ managed to do it...
> 
>     * **Rework README.md.** Will show an about section and an installation section only. Other information will be stated in the script before proceeding.
> 
> 
> That's all I can think of right now. What you need to know right now is that they are working on making Pantheon [distro-agnostic](https://github.com/orgs/elementary/projects/46) and they seem to be halfway there! That means they will make it easier for people on other distros to install Pantheon. I don't know if this script will still be necessary when they complete it. I'll still work on HADRIAN as a fun project.

Yes. They do a great job but i like vanilla arch. Without bloat! But i can live with this!

**Comment by shnflrsc** [comment]
The new version in the [next branch](https://github.com/furesuka/HADRIAN/tree/next) is now ready for testing! The only problems I have no idea how to fix _for now_ is that Wingpanel crashes in the login screen and the background color is black. I would like to know if that problem also occurs in real hardware, so you can open another issue for any problems you encounter.

_Also,_ making an automatic installation script will be trickier than I thought. I'm combining all these scripts and all that could go wrong into one single script, so I may cancel that part.

**Comment by linuxmobile** [comment]
> ombining all these scri

Ok. i will try in few hours! i'm working now!!! but let me check later!!!

Maybe it can help you. They rewritten some packages https://github.com/tearch-linux/pantheon_repo

**Comment by linuxmobile** [comment]
> Wingpanel crashes in the login screen and the background color is black

**Hi. This was fixed installing pantheon-notifications. Everything is working fine! I need to check all stuff. But looks fine. I already try with Virtualbox. But now I will try in real hardware**

**Comment by shnflrsc** [comment]
That's great! How was the experience in real hardware?

**Comment by linuxmobile** [comment]
> That's great! How was the experience in real hardware?

it's working fine. Lightdm start weird.. but with some tweaks you can change the theme and looks nice... 

-  mouse and trackpad settings don't work.
- sometimes when i want to change desktop wallpaper it freeze and i can do anything. I need to reboot (i don't take any log about that)
- Then.. everything is working fine!! only 650 packages. 500mb ram at boot! This is really cool!

You need to add `pantheon-notifications` and `switchboard-plug-pantheon-tweaks` to the script!

**Comment by shnflrsc** [comment]
> mouse and trackpad settings don't work.

Do you mean multi-touch gestures? They worked with the developer of Touchégg to integrate it into Vala. I can't test if Touchégg will work on its own on Arch Linux with Pantheon because I don't have a laptop..
> sometimes when i want to change desktop wallpaper it freeze and i can do anything. I need to reboot (i don't take any log about that)

That's pretty weird. I thought it only happens in the virtual machine, I will have to look into it. (but It may be a problem with switchboard itself, we'll see.)
> You need to add pantheon-notifications and switchboard-plug-pantheon-tweaks to the script!

I added `pantheon-notifications` to Pantheon Base and a new Pantheon Tweaks option in the latest commit, thanks for suggesting that!

**Comment by linuxmobile** [comment]
> Do you mean multi-touch gestures? They worked with the developer of Touchégg to integrate it into Vala. I can't test if Touchégg will work on its own on Arch Linux with Pantheon because I don't have a laptop

No. I mean I can't setup my mouse or any trackpad. The options seems to be broken! When I click under settings/mouse/ settings app crash and close!

**Comment by shnflrsc** [comment]
This seems to be happening because the `org.gnome.settings-daemon.peripherals.mouse` schema is deprecated which Switchboard uses. The package gsettings-desktop-schemas provides it in previous versions but right now it is incompatible. Well, TeArch Linux has a [package](https://gitlab.com/tearch-linux/packages/tearch-packages/gnome-settings-daemon/-/blob/master/PKGBUILD) for that, but I'm afraid of stealing work 😬

**Comment by linuxmobile** [comment]
> This seems to be happening because the `org.gnome.settings-daemon.peripherals.mouse` schema is deprecated which Switchboard uses. The package gsettings-desktop-schemas provides it in previous versions but right now it is incompatible. Well, TeArch Linux has a [package](https://gitlab.com/tearch-linux/packages/tearch-packages/gnome-settings-daemon/-/blob/master/PKGBUILD) for that, but I'm afraid of stealing work 😬

Yeah. Dont worry it's a little bug into the good work you do! People can live with it! Kang is bad haha

**Comment by shnflrsc** [comment]
Haha thanks! The next branch seem to be working well (apart from a few issues out of my reach) and can be merged with main. This issue is also good and done. Enjoy!
